services:
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-network
    command: 
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      
networks:
  postgres-network:
    driver: bridge